# Generated by Django 3.2.18 on 2024-09-06 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_products', '0002_alter_tourproducts_options'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='tour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tour_products.tourproducts'),
        ),
    ]
