# Generated by Django 3.2.18 on 2023-04-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourproducts',
            options={'verbose_name_plural': 'Tour Product'},
        ),
    ]
