# Generated by Django 3.2.18 on 2024-09-17 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_products', '0003_auto_20240913_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourproducts',
            name='category',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
