# Generated by Django 3.2.18 on 2024-09-18 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour_products', '0004_alter_tourproducts_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourproducts',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duration of the tour in days', null=True),
        ),
        migrations.AlterField(
            model_name='tourproducts',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
        migrations.CreateModel(
            name='TourImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tour_images/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tour_products.tourproducts')),
            ],
        ),
    ]
